apiVersion: v1
kind: Pod
metadata:
  name: neo4j-pod
  labels:
    app: neo4j
    course: DSC104_FA20_A00
spec:
  activeDeadlineSeconds: 14400
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: admitcpupods
            operator: In
            values:
            - 'true'
            - 'false'
  containers:
  - name: neo4j
    image: neo4j:4.1
    env:
      - name: NEO4J_AUTH
        value: none
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 2Gi
    ports:
    - containerPort: 7474
    - containerPort: 7687
---
apiVersion: v1
kind: Service
metadata:
  name: my-neo4j
  labels:
    app: neo4j
spec:
  ports:
  - port: 7474
    targetPort: 7474
    name: browser
  - port: 7687
    targetPort: 7687
    name: bolt
  selector:
    app: neo4j