apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
    course: DSC104_FA20_A00
spec:
  activeDeadlineSeconds: 14400
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: admitcpupods
            operator: In
            values:
            - 'true'
            - 'false'
  containers:
  - name: postgres
    image: postgres:12.4
    env:
      - name: POSTGRES_PASSWORD
        value: password
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 2Gi
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: my-postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres