apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
  activeDeadlineSeconds: 14400
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: admitcpupods
            operator: In
            values:
            - 'true'
            - 'false'
  containers:
  - name: redis-master
    image: redis:latest
    command:
      - redis-server
      - "--maxmemory 2mb"
      - "--maxmemory-policy allkeys-lru"
    env:
    - name: MASTER
      value: "true"
    resources:
      requests:
        cpu: 100m
        memory: 2Gi
      limits:
        cpu: 100m
        memory: 2Gi
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
  volumes:
    - name: data
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: my-redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  selector:
    app: redis