apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    course: DSC104_FA20_A00
spec:
  activeDeadlineSeconds: 14400
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: admitcpupods
            operator: In
            values:
            - 'true'
            - 'false'
  containers:
  - name: redis-master
    image: redis:6.0.8
    command:
      - redis-server
      - "--maxmemory 256mb"
      - "--maxmemory-policy noeviction"
    env:
    - name: MASTER
      value: "true"
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: my-redis
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: client
  selector:
    app: redis