apiVersion: v1
kind: Pod
metadata:
  name: solr-pod
  labels:
    app: solr
    course: DSC104_FA20_A00
spec:
  activeDeadlineSeconds: 14400
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: admitcpupods
            operator: In
            values:
            - 'true'
            - 'false'
  containers:
  - name: solr
    image: solr:latest
    command: 
      - "solr-demo"
    resources:
      requests:
        cpu: 200m
        memory: 2Gi
      limits:
        cpu: 500m
        memory: 2Gi
    ports:
    - containerPort: 8983
---
apiVersion: v1
kind: Service
metadata:
  name: my-solr
  labels:
    app: solr
spec:
  ports:
  - port: 8983
    targetPort: 8983
  selector:
    app: solr